//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QidWorkerRole.SIS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdhocSPARateMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AdhocSPARateMaster()
        {
            this.AdhocSPARateSlabs = new HashSet<AdhocSPARateSlab>();
        }
    
        public int ID { get; set; }
        public string AdhocSPARateID { get; set; }
        public string AdhocSPARateCategory { get; set; }
        public string AdhocSPAType { get; set; }
        public string AdhocSPARate { get; set; }
        public Nullable<System.DateTime> ValidFrom { get; set; }
        public Nullable<System.DateTime> ValidTo { get; set; }
        public Nullable<int> AWBID { get; set; }
        public string AWBPrefix { get; set; }
        public string AWBNumber { get; set; }
        public string Origin { get; set; }
        public string Destination { get; set; }
        public string FlightNumber { get; set; }
        public string FlightDate { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<decimal> Volume { get; set; }
        public string Currency { get; set; }
        public string AgentCode { get; set; }
        public string AgentName { get; set; }
        public string Commodity { get; set; }
        public Nullable<bool> Commissionable { get; set; }
        public Nullable<bool> Noncommissionable { get; set; }
        public Nullable<short> ThresholdLimit { get; set; }
        public string Station { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public string FWDName { get; set; }
        public string Remarks { get; set; }
        public string SpecialApproval { get; set; }
        public string Reason { get; set; }
        public string Aproval { get; set; }
        public Nullable<bool> AllIn { get; set; }
        public string WtCategory { get; set; }
        public Nullable<int> Pcs { get; set; }
        public string ShippingAgent { get; set; }
        public Nullable<decimal> Chrgweight { get; set; }
        public string UOM { get; set; }
        public string Shipper { get; set; }
        public string Consignee { get; set; }
        public string ProductType { get; set; }
        public Nullable<decimal> MKTRate { get; set; }
        public Nullable<decimal> MKTFrt { get; set; }
        public Nullable<bool> IsApply { get; set; }
        public Nullable<byte> ApprovalLevel { get; set; }
        public string IssuedBy { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public string AuthorisedBy { get; set; }
        public Nullable<System.DateTime> AuthorisedDate { get; set; }
        public string UpdatebBy { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public string CarrierCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdhocSPARateSlab> AdhocSPARateSlabs { get; set; }
    }
}
