//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QidWorkerRole.SIS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AirWayBill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AirWayBill()
        {
            this.AWBOtherCharges = new HashSet<AWBOtherCharge>();
            this.AWBVATs = new HashSet<AWBVAT>();
        }
    
        public int AirWayBillID { get; set; }
        public int InvoiceHeaderID { get; set; }
        public string BillingCode { get; set; }
        public decimal BatchSequenceNumber { get; set; }
        public decimal RecordSequencewithinBatch { get; set; }
        public System.DateTime AWBDate { get; set; }
        public string AWBIssuingAirline { get; set; }
        public decimal AWBSerialNumber { get; set; }
        public decimal AWBCheckDigit { get; set; }
        public string Origin { get; set; }
        public string Destination { get; set; }
        public string From { get; set; }
        public string To { get; set; }
        public decimal DateOfCarriage { get; set; }
        public decimal WeightCharges { get; set; }
        public Nullable<decimal> OtherCharges { get; set; }
        public Nullable<decimal> AmountSubjectToInterlineServiceCharge { get; set; }
        public Nullable<decimal> InterlineServiceChargePercentage { get; set; }
        public string CurrencyAdjustmentIndicator { get; set; }
        public decimal BilledWeight { get; set; }
        public string ProvisoReqSPA { get; set; }
        public Nullable<decimal> ProratePercentage { get; set; }
        public string PartShipmentIndicator { get; set; }
        public Nullable<decimal> ValuationCharges { get; set; }
        public string KGLBIndicator { get; set; }
        public Nullable<decimal> VATAmount { get; set; }
        public Nullable<decimal> InterlineServiceChargeAmount { get; set; }
        public Nullable<decimal> AWBTotalAmount { get; set; }
        public string CCAindicator { get; set; }
        public string OurReference { get; set; }
        public string AttachmentIndicatorOriginal { get; set; }
        public string AttachmentIndicatorValidated { get; set; }
        public Nullable<decimal> NumberOfAttachments { get; set; }
        public string ISValidationFlag { get; set; }
        public string ReasonCode { get; set; }
        public string ReferenceField1 { get; set; }
        public string ReferenceField2 { get; set; }
        public string ReferenceField3 { get; set; }
        public string ReferenceField4 { get; set; }
        public string ReferenceField5 { get; set; }
        public string AirlineOwnUse { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string LastUpdatedBy { get; set; }
        public System.DateTime LastUpdatedOn { get; set; }
        public string AcceptRejectStatus { get; set; }
        public byte AWBStatusID { get; set; }
        public Nullable<decimal> NFRProftLoss { get; set; }
        public string SKRemarks { get; set; }
        public Nullable<int> RemarkID { get; set; }
        public Nullable<long> AWBID { get; set; }
        public string AWBNumber { get; set; }
        public decimal AcceptedAmount { get; set; }
        public decimal RejectedAmount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AWBOtherCharge> AWBOtherCharges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AWBVAT> AWBVATs { get; set; }
        public virtual InvoiceHeader InvoiceHeader { get; set; }
    }
}
