//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QidWorkerRole.SIS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillingInterlineBMAWBOC
    {
        public int ID { get; set; }
        public int BillingInterlineBMAWBID { get; set; }
        public string OCCode { get; set; }
        public Nullable<decimal> OCCodeValue { get; set; }
        public string VATLabel { get; set; }
        public string VATText { get; set; }
        public Nullable<decimal> VATBaseAmt { get; set; }
        public Nullable<decimal> VATPer { get; set; }
        public Nullable<decimal> VATCalculatedAmt { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime LastUpdatedOn { get; set; }
        public string LastUpdatedBy { get; set; }
    }
}
