//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QidWorkerRole.SIS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillingInterlineFile
    {
        public int ID { get; set; }
        public string AirlineCode { get; set; }
        public Nullable<decimal> VersionNumber { get; set; }
        public string FileName { get; set; }
        public Nullable<int> FileInOutDirection { get; set; }
        public string FilePath { get; set; }
        public string LogFilePath { get; set; }
        public Nullable<decimal> TotalWeightCharges { get; set; }
        public Nullable<decimal> TotalOtherCharges { get; set; }
        public Nullable<decimal> TotalInterlineServiceChargeAmount { get; set; }
        public Nullable<decimal> FileTotalOfNetInvoiceTotal { get; set; }
        public Nullable<decimal> FileTotalOfNetInvoiceBillingTotal { get; set; }
        public Nullable<decimal> TotalValuationCharges { get; set; }
        public Nullable<decimal> TotalVATAmount { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string LastUpdatedBy { get; set; }
        public System.DateTime LastUpdatedOn { get; set; }
    }
}
