//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QidWorkerRole.SIS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillingCodeSubTotal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BillingCodeSubTotal()
        {
            this.BillingCodeSubTotalVATs = new HashSet<BillingCodeSubTotalVAT>();
        }
    
        public int BillingCodeSubTotalID { get; set; }
        public int InvoiceHeaderID { get; set; }
        public string BillingCode { get; set; }
        public Nullable<decimal> TotalWeighCharges { get; set; }
        public Nullable<decimal> TotalOtherCharges { get; set; }
        public Nullable<decimal> TotalInterlineServiceCharge { get; set; }
        public Nullable<decimal> BillingCodeSubTotal1 { get; set; }
        public decimal TotalNumberOfBillingRecords { get; set; }
        public Nullable<decimal> TotalValuationCharges { get; set; }
        public Nullable<decimal> TotalVATAmount { get; set; }
        public decimal TotalNumberOfRecords { get; set; }
        public string BillingCodeSubTotalDescription { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string LastUpdatedBy { get; set; }
        public System.DateTime LastUpdatedOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillingCodeSubTotalVAT> BillingCodeSubTotalVATs { get; set; }
        public virtual InvoiceHeader InvoiceHeader { get; set; }
    }
}
