//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QidWorkerRole.SIS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillingInterlineCMAWB
    {
        public int ID { get; set; }
        public string BillingAirline { get; set; }
        public string BilledAirline { get; set; }
        public string BillingCode { get; set; }
        public decimal BreakdownSrNo { get; set; }
        public Nullable<System.DateTime> AWBDate { get; set; }
        public string AWBIssuingAirline { get; set; }
        public decimal AWBSrNo { get; set; }
        public decimal AWBCheckDigit { get; set; }
        public string Origin { get; set; }
        public string Destination { get; set; }
        public string From { get; set; }
        public string To { get; set; }
        public System.DateTime TransferDate { get; set; }
        public Nullable<decimal> WtChargesCredited { get; set; }
        public Nullable<decimal> ValChargesCredited { get; set; }
        public Nullable<decimal> OCAmtCredited { get; set; }
        public Nullable<decimal> AmtSubISCCredited { get; set; }
        public Nullable<decimal> ISCPerCredited { get; set; }
        public Nullable<decimal> ISCAmtCredited { get; set; }
        public Nullable<decimal> VATAmtCredited { get; set; }
        public Nullable<decimal> TotalAmtCredited { get; set; }
        public string CurrencyAdjInd { get; set; }
        public Nullable<decimal> BilledWt { get; set; }
        public string ProvisoReqSPA { get; set; }
        public Nullable<decimal> ProratePer { get; set; }
        public string PartShipmentInd { get; set; }
        public string KGLBInd { get; set; }
        public string CCaInd { get; set; }
        public string AttachmentIndOri { get; set; }
        public string AttachmentIndValidated { get; set; }
        public Nullable<decimal> NoOfAttachments { get; set; }
        public string ISValidationFlag { get; set; }
        public string ReasonCode { get; set; }
        public string RefField { get; set; }
        public string AirlineOwnUse { get; set; }
        public byte AWBStatusID { get; set; }
        public string CMBillingCode { get; set; }
        public decimal BatchNo { get; set; }
        public decimal SeqNo { get; set; }
        public string CMNumber { get; set; }
        public string CMReasonCode { get; set; }
        public string OurRef { get; set; }
        public string CorrespondenceRefNo { get; set; }
        public string YourInvNo { get; set; }
        public Nullable<decimal> YourInvBillingYear { get; set; }
        public Nullable<decimal> YourInvBillingMonth { get; set; }
        public Nullable<decimal> YourInvBillingPeriod { get; set; }
        public string CMAttachmentIndOri { get; set; }
        public string CMAttachmentIndValidated { get; set; }
        public Nullable<decimal> CMNoOfAttachments { get; set; }
        public string CMAirlineOwnUse { get; set; }
        public string CMISValidationFlag { get; set; }
        public string ReasonRemarks { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string LastUpdatedBy { get; set; }
        public System.DateTime LastUpdatedOn { get; set; }
        public Nullable<bool> IsSIS { get; set; }
        public Nullable<int> RemarkID { get; set; }
        public Nullable<long> AWBID { get; set; }
        public string AWBNumber { get; set; }
        public string CurrencyofBilling { get; set; }
        public string CurrencyofListing { get; set; }
        public Nullable<decimal> ListingtoBillingRate { get; set; }
    }
}
