//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QidWorkerRole.SIS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillingInterlineInvoice
    {
        public int ID { get; set; }
        public Nullable<int> BillingInterlineFileID { get; set; }
        public string BillingAirline { get; set; }
        public string BilledAirline { get; set; }
        public string InvoiceNumber { get; set; }
        public decimal BillingYear { get; set; }
        public decimal BillingMonth { get; set; }
        public decimal PeriodNumber { get; set; }
        public string CurrencyOfListing { get; set; }
        public string CurrencyOfBilling { get; set; }
        public string SettlementMethodIndicator { get; set; }
        public string DigitalSignatureFlag { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public Nullable<decimal> ListingToBillingRate { get; set; }
        public string InvoiceType { get; set; }
        public string InvoiceTemplateLanguage { get; set; }
        public Nullable<System.DateTime> CHDueDate { get; set; }
        public string CHAgreementIndicator { get; set; }
        public string InvoiceFooterDetails { get; set; }
        public Nullable<decimal> TotalWeightCharges { get; set; }
        public Nullable<decimal> TotalOtherCharges { get; set; }
        public Nullable<decimal> TotalInterlineServiceChargeAmount { get; set; }
        public Nullable<decimal> NetInvoiceTotal { get; set; }
        public Nullable<decimal> NetInvoiceBillingTotal { get; set; }
        public Nullable<decimal> TotalValuationCharges { get; set; }
        public Nullable<decimal> TotalVATAmount { get; set; }
        public Nullable<decimal> TotalNetAmountWithoutVAT { get; set; }
        public int InvoiceStatusId { get; set; }
        public bool IsReceivedFromFile { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string LastUpdatedBy { get; set; }
        public System.DateTime LastUpdatedOn { get; set; }
    }
}
