//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QidWorkerRole.SIS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillingInterlineAWBVAT
    {
        public int ID { get; set; }
        public Nullable<int> BillingInterlineAirWayBillID { get; set; }
        public string VATIdentifier { get; set; }
        public string VATLabel { get; set; }
        public string VATText { get; set; }
        public Nullable<decimal> VATBaseAmount { get; set; }
        public Nullable<decimal> VATPercentage { get; set; }
        public Nullable<decimal> VATCalculatedAmount { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string LastUpdatedBy { get; set; }
        public System.DateTime LastUpdatedOn { get; set; }
    }
}
