//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QidWorkerRole.SIS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillingInterlineAWBRateLog
    {
        public int ID { get; set; }
        public Nullable<int> AWBSummaryMasterID { get; set; }
        public string AWBPrefix { get; set; }
        public string AWBNumber { get; set; }
        public string FlightNo { get; set; }
        public System.DateTime FlightDate { get; set; }
        public string Origin { get; set; }
        public string Destination { get; set; }
        public string From { get; set; }
        public string To { get; set; }
        public string CurrencyOfProrateCalculation { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public string ProvisoReqSPA { get; set; }
        public Nullable<int> ProrateFactor { get; set; }
        public Nullable<int> PercentShare { get; set; }
        public string ChargeType { get; set; }
        public Nullable<int> Pieces { get; set; }
        public Nullable<decimal> GWeight { get; set; }
        public Nullable<decimal> CWeight { get; set; }
        public Nullable<bool> IsPrime { get; set; }
        public Nullable<decimal> Freight { get; set; }
        public Nullable<decimal> FreightTax { get; set; }
        public Nullable<decimal> RatePerKg { get; set; }
        public string PayMode { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<decimal> Proration { get; set; }
        public Nullable<decimal> MKTFrt { get; set; }
        public Nullable<decimal> MKTTax { get; set; }
        public string IATARateClass { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string LastUpdatedBy { get; set; }
        public System.DateTime LastUpdatedOn { get; set; }
    }
}
