//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QidWorkerRole.SIS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalendarMaster
    {
        public int CalendarMasterID { get; set; }
        public System.DateTime BillingPeriod { get; set; }
        public Nullable<System.DateTime> PeriodStartDate { get; set; }
        public Nullable<System.DateTime> PeriodEndDate { get; set; }
        public string ClearingHouse { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string LastUpdatedBy { get; set; }
        public System.DateTime LastUpdatedOn { get; set; }
    }
}
