//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QidWorkerRole.SIS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMAirWayBill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CMAirWayBill()
        {
            this.CMAWBOtherCharges = new HashSet<CMAWBOtherCharge>();
            this.CMAWBProrateLadders = new HashSet<CMAWBProrateLadder>();
            this.CMAWBVATs = new HashSet<CMAWBVAT>();
        }
    
        public int CMAirWayBillID { get; set; }
        public int CreditMemoID { get; set; }
        public string BillingCode { get; set; }
        public decimal BreakdownSerialNumber { get; set; }
        public Nullable<System.DateTime> AWBDate { get; set; }
        public string AWBIssuingAirline { get; set; }
        public decimal AWBSerialNumber { get; set; }
        public decimal AWBCheckDigit { get; set; }
        public string Origin { get; set; }
        public string Destination { get; set; }
        public string From { get; set; }
        public string To { get; set; }
        public System.DateTime DateOfCarriage { get; set; }
        public Nullable<decimal> WeightChargesCredited { get; set; }
        public Nullable<decimal> ValuationChargesCredited { get; set; }
        public Nullable<decimal> OtherChargesAmountCredited { get; set; }
        public Nullable<decimal> AmountSubjectedToISCCredited { get; set; }
        public Nullable<decimal> ISCPercentCredited { get; set; }
        public Nullable<decimal> ISCAmountCredited { get; set; }
        public Nullable<decimal> VATAmountCredited { get; set; }
        public Nullable<decimal> TotalAmountCredited { get; set; }
        public string CurrencyAdjustmentIndicator { get; set; }
        public Nullable<decimal> BilledWeight { get; set; }
        public string ProvisoReqSPA { get; set; }
        public Nullable<decimal> ProratePercent { get; set; }
        public string PartShipmentIndicator { get; set; }
        public string KGLBIndicator { get; set; }
        public string CCaIndicator { get; set; }
        public string AttachmentIndicatorOriginal { get; set; }
        public string AttachmentIndicatorValidated { get; set; }
        public Nullable<decimal> NumberOfAttachments { get; set; }
        public string ISValidationFlag { get; set; }
        public string ReasonCode { get; set; }
        public string ReferenceField1 { get; set; }
        public string ReferenceField2 { get; set; }
        public string ReferenceField3 { get; set; }
        public string ReferenceField4 { get; set; }
        public string ReferenceField5 { get; set; }
        public string AirlineOwnUse { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string LastUpdatedBy { get; set; }
        public System.DateTime LastUpdatedOn { get; set; }
        public byte AWBStatusID { get; set; }
        public Nullable<decimal> NFRProftLoss { get; set; }
        public string SKRemarks { get; set; }
        public Nullable<int> RemarkID { get; set; }
        public Nullable<long> AWBID { get; set; }
        public string AWBNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CMAWBOtherCharge> CMAWBOtherCharges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CMAWBProrateLadder> CMAWBProrateLadders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CMAWBVAT> CMAWBVATs { get; set; }
        public virtual CreditMemo CreditMemo { get; set; }
    }
}
