//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QidWorkerRole.SIS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMAWBProrateLadder
    {
        public int CMAWBProrateLadderID { get; set; }
        public int CMAirWayBillID { get; set; }
        public string CurrencyOfProrateCalculation { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public string FromSector { get; set; }
        public string ToSector { get; set; }
        public string CarrierPrefix { get; set; }
        public string ProvisoReqSpa { get; set; }
        public Nullable<decimal> ProrateFactor { get; set; }
        public Nullable<decimal> PercentShare { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string LastUpdatedBy { get; set; }
        public System.DateTime LastUpdatedOn { get; set; }
    
        public virtual CMAirWayBill CMAirWayBill { get; set; }
    }
}
