//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QidWorkerRole.SIS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditMemo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CreditMemo()
        {
            this.CMAirWayBills = new HashSet<CMAirWayBill>();
            this.CMVATs = new HashSet<CMVAT>();
        }
    
        public int CreditMemoID { get; set; }
        public int InvoiceHeaderID { get; set; }
        public string BillingCode { get; set; }
        public decimal BatchSequenceNumber { get; set; }
        public decimal RecordSequenceWithinBatch { get; set; }
        public string CreditMemoNumber { get; set; }
        public string ReasonCode { get; set; }
        public string OurRef { get; set; }
        public string CorrespondenceRefNumber { get; set; }
        public string YourInvoiceNumber { get; set; }
        public Nullable<decimal> YourInvoiceBillingYear { get; set; }
        public Nullable<decimal> YourInvoiceBillingMonth { get; set; }
        public Nullable<decimal> YourInvoiceBillingPeriod { get; set; }
        public Nullable<decimal> TotalWeightChargesCredited { get; set; }
        public Nullable<decimal> TotalValuationAmountCredited { get; set; }
        public Nullable<decimal> TotalOtherChargeAmountCredited { get; set; }
        public Nullable<decimal> TotalISCAmountCredited { get; set; }
        public Nullable<decimal> TotalVATAmountCredited { get; set; }
        public Nullable<decimal> NetCreditedAmount { get; set; }
        public string AttachmentIndicatorOriginal { get; set; }
        public string AttachmentIndicatorValidated { get; set; }
        public Nullable<decimal> NumberOfAttachments { get; set; }
        public string AirlineOwnUse { get; set; }
        public string ISValidationFlag { get; set; }
        public string ReasonRemarks { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime LastUpdatedOn { get; set; }
        public string LastUpdatedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CMAirWayBill> CMAirWayBills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CMVAT> CMVATs { get; set; }
        public virtual InvoiceHeader InvoiceHeader { get; set; }
    }
}
