//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QidWorkerRole.SIS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class InterlineInvoiceCollectionDetail
    {
        public int ID { get; set; }
        public int InvoiceHeaderID { get; set; }
        public string InvoiceNumber { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public string BillingAirline { get; set; }
        public string BilledAirline { get; set; }
        public Nullable<short> BillingYear { get; set; }
        public Nullable<byte> BillingMonth { get; set; }
        public Nullable<byte> PeriodNumber { get; set; }
        public string SettlementMethodIndicator { get; set; }
        public string InvoiceType { get; set; }
        public string InvoiceCurrency { get; set; }
        public decimal WeightCharges { get; set; }
        public decimal ValuationCharges { get; set; }
        public decimal OtherCharges { get; set; }
        public decimal VATAmount { get; set; }
        public decimal ISCAmount { get; set; }
        public decimal NetInvoiceBillingTotal { get; set; }
        public bool IsSIS { get; set; }
        public decimal CollectedAmtInInvoiceCurrency { get; set; }
        public decimal BalanceAmtInInvoiceCurrency { get; set; }
        public string CollectionCurrency { get; set; }
        public decimal CollectionCurrencyAmt { get; set; }
        public decimal ConversionRate { get; set; }
        public Nullable<System.DateTime> ConversionDate { get; set; }
        public string PaymentType { get; set; }
        public string CardType { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public string ChequeDDNumber { get; set; }
        public Nullable<System.DateTime> ChequeDate { get; set; }
        public string BankName { get; set; }
        public Nullable<System.DateTime> DepositDate { get; set; }
        public string ORRecieptNo { get; set; }
        public string TINNumber { get; set; }
        public string Remarks { get; set; }
        public string CollectedAtStation { get; set; }
        public bool IsDeleted { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string LastUpdatedBy { get; set; }
        public System.DateTime LastUpdatedOn { get; set; }
    }
}
