//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QidWorkerRole.SIS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class InterlineAuditLog
    {
        public int SerialNumer { get; set; }
        public Nullable<int> AWBID { get; set; }
        public string AWBPrefix { get; set; }
        public string AWBNumber { get; set; }
        public string AWBOrigin { get; set; }
        public string AWBDestination { get; set; }
        public string FlightNo { get; set; }
        public string FlightDate { get; set; }
        public string FlightOrigin { get; set; }
        public string FlightDestination { get; set; }
        public string CarrierCode { get; set; }
        public Nullable<int> Pieces { get; set; }
        public Nullable<decimal> ChargeableWeight { get; set; }
        public string UOM { get; set; }
        public string ProrationType { get; set; }
        public Nullable<int> ProrateFactor { get; set; }
        public string SPAId { get; set; }
        public Nullable<decimal> ProFactorPercentage { get; set; }
        public Nullable<decimal> AppliedPercentage { get; set; }
        public string Currency { get; set; }
        public Nullable<decimal> SPAFreight { get; set; }
        public Nullable<decimal> ValuationCharge { get; set; }
        public Nullable<decimal> Incentive { get; set; }
        public Nullable<decimal> CommisionAmount { get; set; }
        public Nullable<decimal> OCDC { get; set; }
        public Nullable<decimal> OCDA { get; set; }
        public Nullable<decimal> ISCAmountApplicable { get; set; }
        public Nullable<decimal> ISCPercentage { get; set; }
        public Nullable<decimal> ISCAmount { get; set; }
        public Nullable<decimal> IATATax { get; set; }
        public Nullable<decimal> NetAmount { get; set; }
        public string AWBSTATUS { get; set; }
        public string ActionPerformed { get; set; }
        public Nullable<System.DateTime> ActionPerformedOnDate { get; set; }
        public string BillingAirline { get; set; }
        public string BilledAirline { get; set; }
        public string InvoiceNumber { get; set; }
        public string BillingPeriod { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> IsVisible { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string MemoType { get; set; }
        public string MemoNumber { get; set; }
        public Nullable<bool> RejectionStage { get; set; }
    }
}
