//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QidWorkerRole.SIS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceTotal
    {
        public int InvoiceTotalID { get; set; }
        public int InvoiceHeaderID { get; set; }
        public Nullable<decimal> TotalWeightCharges { get; set; }
        public Nullable<decimal> TotalOtherCharges { get; set; }
        public Nullable<decimal> TotalInterlineServiceChargeAmount { get; set; }
        public Nullable<decimal> NetInvoiceTotal { get; set; }
        public Nullable<decimal> NetInvoiceBillingTotal { get; set; }
        public decimal TotalNumberOfBillingRecords { get; set; }
        public Nullable<decimal> TotalValuationCharges { get; set; }
        public Nullable<decimal> TotalVATAmount { get; set; }
        public decimal TotalNumberOfRecords { get; set; }
        public Nullable<decimal> TotalNetAmountWithoutVAT { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string LastUpdatedBy { get; set; }
        public System.DateTime LastUpdatedOn { get; set; }
    
        public virtual InvoiceHeader InvoiceHeader { get; set; }
    }
}
