//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QidWorkerRole.SIS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InvoiceHeader()
        {
            this.AirWayBills = new HashSet<AirWayBill>();
            this.BillingCodeSubTotals = new HashSet<BillingCodeSubTotal>();
            this.BillingMemoes = new HashSet<BillingMemo>();
            this.CreditMemoes = new HashSet<CreditMemo>();
            this.InvoiceTotalVATs = new HashSet<InvoiceTotalVAT>();
            this.InvoiceTotals = new HashSet<InvoiceTotal>();
            this.RejectionMemoes = new HashSet<RejectionMemo>();
        }
    
        public int InvoiceHeaderID { get; set; }
        public Nullable<int> FileHeaderID { get; set; }
        public string BillingAirline { get; set; }
        public string BilledAirline { get; set; }
        public string InvoiceNumber { get; set; }
        public decimal BillingYear { get; set; }
        public decimal BillingMonth { get; set; }
        public decimal PeriodNumber { get; set; }
        public string CurrencyofListing { get; set; }
        public string CurrencyofBilling { get; set; }
        public string SettlementMethodIndicator { get; set; }
        public string DigitalSignatureFlag { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public Nullable<decimal> ListingtoBillingRate { get; set; }
        public string SuspendedInvoiceFlag { get; set; }
        public string BillingAirlineLocationID { get; set; }
        public string BilledAirlineLocationID { get; set; }
        public string InvoiceType { get; set; }
        public string InvoiceTemplateLanguage { get; set; }
        public string CHDueDate { get; set; }
        public string CHAgreementIndicator { get; set; }
        public string InvoiceFooterDetails { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string LastUpdatedBy { get; set; }
        public System.DateTime LastUpdatedOn { get; set; }
        public Nullable<int> InvoiceStatusId { get; set; }
        public bool IsReceivedFromFile { get; set; }
        public Nullable<bool> IsSIS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AirWayBill> AirWayBills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillingCodeSubTotal> BillingCodeSubTotals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillingMemo> BillingMemoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CreditMemo> CreditMemoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceTotalVAT> InvoiceTotalVATs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceTotal> InvoiceTotals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RejectionMemo> RejectionMemoes { get; set; }
    }
}
