//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QidWorkerRole.SIS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ISValidationDetailErrorReport
    {
        public int ID { get; set; }
        public Nullable<int> SerialNo { get; set; }
        public string BillingEntityCode { get; set; }
        public Nullable<int> BillingYear { get; set; }
        public Nullable<int> BillingMonth { get; set; }
        public Nullable<int> BillingPeriod { get; set; }
        public string BillingCategory { get; set; }
        public string BillingFileName { get; set; }
        public Nullable<System.DateTime> BillingFileSubmissionDate { get; set; }
        public string SubmissionFormat { get; set; }
        public string BilledEntityCode { get; set; }
        public string InvoiceNumber { get; set; }
        public string CGOBillingCode { get; set; }
        public Nullable<int> CGOBatchNumber { get; set; }
        public Nullable<int> CGOSeqNumber { get; set; }
        public string MainDocNo { get; set; }
        public string LinkedDocNo { get; set; }
        public string ErrorCode { get; set; }
        public string ErrorLevel { get; set; }
        public string FieldName { get; set; }
        public string FieldValue { get; set; }
        public string ErrorDescription { get; set; }
        public string ErrorStatus { get; set; }
        public Nullable<int> ValidationForAWBID { get; set; }
        public string ValidationForAWBIDFromTable { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string LastUpdatedBy { get; set; }
        public System.DateTime LastUpdatedOn { get; set; }
        public string CGOBlank { get; set; }
    }
}
