//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QidWorkerRole.SIS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProrationOverrideRouteDetail
    {
        public int ID { get; set; }
        public Nullable<int> AWBID { get; set; }
        public string AWBPrefix { get; set; }
        public string AWBNumber { get; set; }
        public Nullable<int> AWBPcs { get; set; }
        public Nullable<decimal> AWBChWeight { get; set; }
        public Nullable<decimal> AWBGrWeight { get; set; }
        public string AWBOrg { get; set; }
        public string AWBDest { get; set; }
        public string FltOrg { get; set; }
        public string FtlDest { get; set; }
        public string FtlPrefix { get; set; }
        public string FltCarrierCode { get; set; }
        public string FltNo { get; set; }
        public Nullable<System.DateTime> FltDate { get; set; }
        public Nullable<int> FltPcs { get; set; }
        public Nullable<decimal> FltChWeight { get; set; }
        public Nullable<decimal> FltGrWeight { get; set; }
        public string RouteStatus { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string LastUpdatedBy { get; set; }
        public System.DateTime LastUpdatedOn { get; set; }
    }
}
