//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QidWorkerRole.SIS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReferenceData
    {
        public int ReferenceDataID { get; set; }
        public string AirlineCode { get; set; }
        public string CompanyLegalName { get; set; }
        public string TaxVATRegistrationID { get; set; }
        public string AdditionalTaxVATRegistrationID { get; set; }
        public string CompanyRegistrationID { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string AddressLine3 { get; set; }
        public string CityName { get; set; }
        public string SubDivisionCode { get; set; }
        public string SubDivisionName { get; set; }
        public string CountryCode { get; set; }
        public string CountryName { get; set; }
        public string PostalCode { get; set; }
        public string OrganizationDesignator { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string LastUpdatedBy { get; set; }
        public System.DateTime LastUpdatedOn { get; set; }
    }
}
