//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QidWorkerRole.SIS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RejectionMemo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RejectionMemo()
        {
            this.RMAirWayBills = new HashSet<RMAirWayBill>();
            this.RMVATs = new HashSet<RMVAT>();
        }
    
        public int RejectionMemoID { get; set; }
        public int InvoiceHeaderID { get; set; }
        public string BillingCode { get; set; }
        public decimal BatchsequenceNumber { get; set; }
        public decimal RecordSequenceWithinBatch { get; set; }
        public string RejectionMemoNumber { get; set; }
        public decimal RejectionStage { get; set; }
        public string ReasonCode { get; set; }
        public string AirlineOwnUse { get; set; }
        public string YourInvoiceNumber { get; set; }
        public Nullable<decimal> YourInvoiceBillingYear { get; set; }
        public Nullable<decimal> YourInvoiceBillingMonth { get; set; }
        public Nullable<decimal> YourInvoiceBillingPeriod { get; set; }
        public string YourRejectionMemoNumber { get; set; }
        public string BMCMIndicator { get; set; }
        public string YourBMCMNumber { get; set; }
        public Nullable<decimal> TotalWeightChargesBilled { get; set; }
        public Nullable<decimal> TotalWeightChargesAccepted { get; set; }
        public Nullable<decimal> TotalWeightChargesDifference { get; set; }
        public Nullable<decimal> TotalValuationChargesBilled { get; set; }
        public Nullable<decimal> TotalValuationChargesAccepted { get; set; }
        public Nullable<decimal> TotalValuationChargesDifference { get; set; }
        public Nullable<decimal> TotalOtherChargesAmountBilled { get; set; }
        public Nullable<decimal> TotalOtherChargesAmountAccepted { get; set; }
        public Nullable<decimal> TotalOtherChargesDifference { get; set; }
        public Nullable<decimal> TotalISCAmountAllowed { get; set; }
        public Nullable<decimal> TotalISCAmountAccepted { get; set; }
        public Nullable<decimal> TotalISCAmountDifference { get; set; }
        public Nullable<decimal> TotalVATAmountBilled { get; set; }
        public Nullable<decimal> TotalVATAmountAccepted { get; set; }
        public Nullable<decimal> TotalVATAmountDifference { get; set; }
        public Nullable<decimal> TotalNetRejectAmount { get; set; }
        public string AttachmentIndicatorOriginal { get; set; }
        public string AttachmentIndicatorValidated { get; set; }
        public Nullable<decimal> NumberOfAttachments { get; set; }
        public string ISValidationFlag { get; set; }
        public string OurRef { get; set; }
        public string ReasonRemarks { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string LastUpdatedBy { get; set; }
        public System.DateTime LastUpdatedOn { get; set; }
        public string CorrespondenceRefNo { get; set; }
    
        public virtual InvoiceHeader InvoiceHeader { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RMAirWayBill> RMAirWayBills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RMVAT> RMVATs { get; set; }
    }
}
