//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QidWorkerRole.SIS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RMAirWayBill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RMAirWayBill()
        {
            this.RMAWBOtherCharges = new HashSet<RMAWBOtherCharge>();
            this.RMAWBProrateLadders = new HashSet<RMAWBProrateLadder>();
            this.RMAWBVATs = new HashSet<RMAWBVAT>();
        }
    
        public int RMAirWayBillID { get; set; }
        public int RejectionMemoID { get; set; }
        public string BillingCode { get; set; }
        public decimal BreakdownSerialNumber { get; set; }
        public System.DateTime AWBDate { get; set; }
        public string AWBIssuingAirline { get; set; }
        public decimal AWBSerialNumber { get; set; }
        public decimal AWBCheckDigit { get; set; }
        public string ConsignmentOrigin { get; set; }
        public string ConsignmentDestination { get; set; }
        public string CarriageFrom { get; set; }
        public string CarriageTo { get; set; }
        public System.DateTime TransferDate { get; set; }
        public Nullable<decimal> WeightChargesBilled { get; set; }
        public Nullable<decimal> WeightChargesAccepted { get; set; }
        public Nullable<decimal> WeightChargesDifference { get; set; }
        public Nullable<decimal> ValuationChargesBilled { get; set; }
        public Nullable<decimal> ValuationChargesAccepted { get; set; }
        public Nullable<decimal> ValuationChargesDifference { get; set; }
        public Nullable<decimal> OtherChargesAmountBilled { get; set; }
        public Nullable<decimal> OtherChargesAmountAccepted { get; set; }
        public Nullable<decimal> OtherChargesDifference { get; set; }
        public Nullable<decimal> AmountSubjectedToISCAllowed { get; set; }
        public Nullable<decimal> AmountSubjectedToISCAccepted { get; set; }
        public Nullable<decimal> ISCPercentageAllowed { get; set; }
        public Nullable<decimal> ISCPercentageAccepted { get; set; }
        public Nullable<decimal> ISCAmountAllowed { get; set; }
        public Nullable<decimal> ISCAmountAccepted { get; set; }
        public Nullable<decimal> ISCAmountDifference { get; set; }
        public Nullable<decimal> VATAmountBilled { get; set; }
        public Nullable<decimal> VATAmountAccepted { get; set; }
        public Nullable<decimal> VATAmountDifference { get; set; }
        public Nullable<decimal> NetRejectAmount { get; set; }
        public string CurrencyAdjustmentIndicator { get; set; }
        public Nullable<decimal> BilledActualFlownWeight { get; set; }
        public string ProvisoReqSPA { get; set; }
        public Nullable<decimal> ProratePercentage { get; set; }
        public string PartShipmentIndicator { get; set; }
        public string KGLBIndicator { get; set; }
        public string CCAindicator { get; set; }
        public string OurReference { get; set; }
        public string AttachmentIndicatorOriginal { get; set; }
        public string AttachmentIndicatorValidated { get; set; }
        public Nullable<decimal> NumberOfAttachments { get; set; }
        public string ISValidationFlag { get; set; }
        public string ReasonCode { get; set; }
        public string ReferenceField1 { get; set; }
        public string ReferenceField2 { get; set; }
        public string ReferenceField3 { get; set; }
        public string ReferenceField4 { get; set; }
        public string ReferenceField5 { get; set; }
        public string AirlineOwnUse { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string LastUpdatedBy { get; set; }
        public System.DateTime LastUpdatedOn { get; set; }
        public string AcceptRejectStatus { get; set; }
        public byte AWBStatusID { get; set; }
        public string RejectedFromTable { get; set; }
        public Nullable<int> RejectedAWBID { get; set; }
        public Nullable<decimal> NFRProftLoss { get; set; }
        public string SKRemarks { get; set; }
        public Nullable<int> RemarkID { get; set; }
        public Nullable<long> AWBID { get; set; }
        public string AWBNumber { get; set; }
    
        public virtual RejectionMemo RejectionMemo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RMAWBOtherCharge> RMAWBOtherCharges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RMAWBProrateLadder> RMAWBProrateLadders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RMAWBVAT> RMAWBVATs { get; set; }
    }
}
