//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QidWorkerRole.SIS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RMAWBOtherCharge
    {
        public int RMAWBOtherChargesID { get; set; }
        public int RMAirWayBillID { get; set; }
        public string OtherChargeCode { get; set; }
        public Nullable<decimal> OtherChargeCodeValue { get; set; }
        public string VATLabel { get; set; }
        public string VATText { get; set; }
        public Nullable<decimal> VATbaseamount { get; set; }
        public Nullable<decimal> VATpercentage { get; set; }
        public Nullable<decimal> VATcalculatedamount { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime LastUpdatedOn { get; set; }
        public string LastUpdatedBy { get; set; }
    
        public virtual RMAirWayBill RMAirWayBill { get; set; }
    }
}
