//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QidWorkerRole.SIS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAPInterlinePayableReceivable
    {
        public int ID { get; set; }
        public Nullable<int> AWBID { get; set; }
        public string AWBNumber { get; set; }
        public string AWBStatus { get; set; }
        public string ClearanceMonth { get; set; }
        public Nullable<int> Period { get; set; }
        public string BilledAirline { get; set; }
        public string BillingAirline { get; set; }
        public string InvoiceNumber { get; set; }
        public string PayableReceivables { get; set; }
        public string Currency { get; set; }
        public Nullable<decimal> WtCharges { get; set; }
        public Nullable<decimal> ValCharges { get; set; }
        public Nullable<decimal> OtherCharges { get; set; }
        public Nullable<decimal> ISCAmount { get; set; }
        public Nullable<decimal> VATAmount { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public string Origin { get; set; }
        public string Destination { get; set; }
        public Nullable<System.DateTime> AWBDate { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string Identifier { get; set; }
    }
}
