//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QidWorkerRole.SIS.DAL
{
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class SISDBEntities : DbContext
    {
        //public SISDBEntities()
        //    : base("name=SISDBEntities")
        //{
        //}

        // NEW constructor accepting full connection string
        public SISDBEntities(string efConnectionString)
            : base(efConnectionString)
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdhocSPARateMaster> AdhocSPARateMasters { get; set; }
        public virtual DbSet<AdhocSPARateSlab> AdhocSPARateSlabs { get; set; }
        public virtual DbSet<AdhocSPARemark> AdhocSPARemarks { get; set; }
        public virtual DbSet<BillingInterlineAirWayBill> BillingInterlineAirWayBills { get; set; }
        public virtual DbSet<BillingInterlineAWBOC> BillingInterlineAWBOCs { get; set; }
        public virtual DbSet<BillingInterlineAWBRateLog> BillingInterlineAWBRateLogs { get; set; }
        public virtual DbSet<BillingInterlineAWBVAT> BillingInterlineAWBVATs { get; set; }
        public virtual DbSet<BillingInterlineBMAWB> BillingInterlineBMAWBs { get; set; }
        public virtual DbSet<BillingInterlineBMAWBOC> BillingInterlineBMAWBOCs { get; set; }
        public virtual DbSet<BillingInterlineBMAWBProrateLadder> BillingInterlineBMAWBProrateLadders { get; set; }
        public virtual DbSet<BillingInterlineBMAWBVAT> BillingInterlineBMAWBVATs { get; set; }
        public virtual DbSet<BillingInterlineCMAWB> BillingInterlineCMAWBs { get; set; }
        public virtual DbSet<BillingInterlineCMAWBOC> BillingInterlineCMAWBOCs { get; set; }
        public virtual DbSet<BillingInterlineCMAWBProrateLadder> BillingInterlineCMAWBProrateLadders { get; set; }
        public virtual DbSet<BillingInterlineCMAWBVAT> BillingInterlineCMAWBVATs { get; set; }
        public virtual DbSet<BillingInterlineFile> BillingInterlineFiles { get; set; }
        public virtual DbSet<BillingInterlineInvoice> BillingInterlineInvoices { get; set; }
        public virtual DbSet<BillingInterlineInvoiceVAT> BillingInterlineInvoiceVATs { get; set; }
        public virtual DbSet<BillingInterlineRMAWB> BillingInterlineRMAWBs { get; set; }
        public virtual DbSet<BillingInterlineRMAWBOC> BillingInterlineRMAWBOCs { get; set; }
        public virtual DbSet<BillingInterlineRMAWBProrateLadder> BillingInterlineRMAWBProrateLadders { get; set; }
        public virtual DbSet<BillingInterlineRMAWBVAT> BillingInterlineRMAWBVATs { get; set; }
        public virtual DbSet<InterlineAuditLog> InterlineAuditLogs { get; set; }
        public virtual DbSet<InterlineInvoiceCollectionDetail> InterlineInvoiceCollectionDetails { get; set; }
        public virtual DbSet<InterlineRemark> InterlineRemarks { get; set; }
        public virtual DbSet<ProrationOverrideRouteDetail> ProrationOverrideRouteDetails { get; set; }
        public virtual DbSet<SAPInterlinePayableReceivable> SAPInterlinePayableReceivables { get; set; }
        public virtual DbSet<APIIPWhitelist> APIIPWhitelists { get; set; }
        public virtual DbSet<AirWayBill> AirWayBills { get; set; }
        public virtual DbSet<AWBOtherCharge> AWBOtherCharges { get; set; }
        public virtual DbSet<AWBVAT> AWBVATs { get; set; }
        public virtual DbSet<BillingCodeSubTotal> BillingCodeSubTotals { get; set; }
        public virtual DbSet<BillingCodeSubTotalVAT> BillingCodeSubTotalVATs { get; set; }
        public virtual DbSet<BillingMemo> BillingMemoes { get; set; }
        public virtual DbSet<BMAirWayBill> BMAirWayBills { get; set; }
        public virtual DbSet<BMAWBOtherCharge> BMAWBOtherCharges { get; set; }
        public virtual DbSet<BMAWBProrateLadder> BMAWBProrateLadders { get; set; }
        public virtual DbSet<BMAWBVAT> BMAWBVATs { get; set; }
        public virtual DbSet<BMVAT> BMVATs { get; set; }
        public virtual DbSet<CalendarMaster> CalendarMasters { get; set; }
        public virtual DbSet<CMAirWayBill> CMAirWayBills { get; set; }
        public virtual DbSet<CMAWBOtherCharge> CMAWBOtherCharges { get; set; }
        public virtual DbSet<CMAWBProrateLadder> CMAWBProrateLadders { get; set; }
        public virtual DbSet<CMAWBVAT> CMAWBVATs { get; set; }
        public virtual DbSet<CMVAT> CMVATs { get; set; }
        public virtual DbSet<CreditMemo> CreditMemoes { get; set; }
        public virtual DbSet<FileHeader> FileHeaders { get; set; }
        public virtual DbSet<FileTotal> FileTotals { get; set; }
        public virtual DbSet<InterlineStatusMaster> InterlineStatusMasters { get; set; }
        public virtual DbSet<InvoiceHeader> InvoiceHeaders { get; set; }
        public virtual DbSet<InvoiceTotal> InvoiceTotals { get; set; }
        public virtual DbSet<InvoiceTotalVAT> InvoiceTotalVATs { get; set; }
        public virtual DbSet<ISValidationDetailErrorReport> ISValidationDetailErrorReports { get; set; }
        public virtual DbSet<ISValidationFileHeader> ISValidationFileHeaders { get; set; }
        public virtual DbSet<ISValidationSummaryReport> ISValidationSummaryReports { get; set; }
        public virtual DbSet<ReasonCodeMaster> ReasonCodeMasters { get; set; }
        public virtual DbSet<ReferenceData> ReferenceDatas { get; set; }
        public virtual DbSet<RejectionMemo> RejectionMemoes { get; set; }
        public virtual DbSet<RMAirWayBill> RMAirWayBills { get; set; }
        public virtual DbSet<RMAWBOtherCharge> RMAWBOtherCharges { get; set; }
        public virtual DbSet<RMAWBProrateLadder> RMAWBProrateLadders { get; set; }
        public virtual DbSet<RMAWBVAT> RMAWBVATs { get; set; }
        public virtual DbSet<RMVAT> RMVATs { get; set; }
    }
}
