//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QidWorkerRole.SIS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WF_LG04_File
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WF_LG04_File()
        {
            this.WF_LG04_Header = new HashSet<WF_LG04_Header>();
        }
    
        public long Id { get; set; }
        public string FileName { get; set; }
        public long BatchId { get; set; }
        public bool IsActive { get; set; }
        public bool IsTransferToFTP { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> AcceptedDate { get; set; }
        public string TxtFileURL { get; set; }
        public string ExcelFileURL { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public bool IsInterLine { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WF_LG04_Header> WF_LG04_Header { get; set; }
    }
}
