//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QidWorkerRole.SIS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WF_LG04_Header
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WF_LG04_Header()
        {
            this.WF_LG04_Line = new HashSet<WF_LG04_Line>();
        }
    
        public long Id { get; set; }
        public long FileId { get; set; }
        public string JournalType { get; set; }
        public long InvoiceId { get; set; }
        public string InvoiceNo { get; set; }
        public string AparId { get; set; }
        public string BatchId { get; set; }
        public string Client { get; set; }
        public string ConfirmDate { get; set; }
        public string Currency { get; set; }
        public string LineNo { get; set; }
        public string LongInfo1 { get; set; }
        public string LongInfo2 { get; set; }
        public string OrderDate { get; set; }
        public string OrderId { get; set; }
        public string OrderType { get; set; }
        public string Period { get; set; }
        public string Responsible { get; set; }
        public string InvoiceStatus { get; set; }
        public string TransType { get; set; }
        public string VoucherType { get; set; }
        public string HeaderRecord { get; set; }
        public bool IsActive { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> AcceptedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public bool IsInterLine { get; set; }
        public string ExternalOrderRef { get; set; }
    
        public virtual WF_LG04_File WF_LG04_File { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WF_LG04_Line> WF_LG04_Line { get; set; }
    }
}
