//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QidWorkerRole.SIS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WF_LG04_Line
    {
        public long Id { get; set; }
        public string JournalType { get; set; }
        public long HeaderId { get; set; }
        public long FileId { get; set; }
        public long InvoiceId { get; set; }
        public Nullable<int> AWBAuditId { get; set; }
        public Nullable<int> AWBId { get; set; }
        public string AwbPrefix { get; set; }
        public string AwbNo { get; set; }
        public string InvoiceNo { get; set; }
        public string Account { get; set; }
        public string AmountSet { get; set; }
        public string ArticleDescr { get; set; }
        public string Article { get; set; }
        public string BatchId { get; set; }
        public string Client { get; set; }
        public Nullable<decimal> CurrencyAmount { get; set; }
        public string Dim_1 { get; set; }
        public string Dim_6 { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> DiscountPercent { get; set; }
        public string LineNo { get; set; }
        public string OrderId { get; set; }
        public string Period { get; set; }
        public string SequenceNo { get; set; }
        public string ShortInfo { get; set; }
        public string LineStatus { get; set; }
        public string TransType { get; set; }
        public string UnitCode { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public string VoucherType { get; set; }
        public string LineRecord { get; set; }
        public bool IsActive { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> AcceptedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public bool IsInterLine { get; set; }
        public string UnitValue { get; set; }
        public string ExternalOrderRef { get; set; }
    
        public virtual WF_LG04_Header WF_LG04_Header { get; set; }
    }
}
